name: PHP syntax

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-lint:
    name: Linting with overtrue/phplint

    runs-on: ubuntu-latest

    steps:
      - name: Lint PHP files

        uses: overtrue/phplint@main
        with:
          path: .
          options: --exclude=vendor
